[package]
name = "sntk_bytecode"
version = "0.0.0"
edition = "2021"
authors = ["ky0422 (Kim Jun Young)"]
description = "Byte code library for Sanetaka (sntk) programming language"
license = "MIT"
repository = "https://github.com/ky0422/sanetaka"
